export const projectData = [
  // {
  //   title: "Social Media",
  //   desc: "MERN social media app.",
  //   hostURL: "https://social-jifg.onrender.com/",
  //   gitURL: "https://github.com/sijan17/social-frontend.git",
  //   cover: "social-cover.png",
  //   images: [
  //     "social/social-mob-1.png",
  //     "social/social-mob-2.png",
  //     "social/social-mob-3.png",
  //     "social/social-1.png",
  //     "social/social.png",
  //   ],
  // },
  {
    title: "Blog Nest",
    desc: "Blog site build using NextJs and ExpressJS",
    hostURL: "https://blog-nest-woad.vercel.app/",
    gitURL: "https://github.com/yube01/blog_nest/tree/prod",
    cover: "blognest.jpg",
    // images: ["chess/chess-1.png", "chess/chess-2.png"],
  },
  {
    title: "NepNewz",
    desc: "News Portal site build using NextJs",
    hostURL: "https://nep-newz-api.vercel.app/",
    gitURL: "https://github.com/yube01",
    cover: "nepnews.jpg",
    // images: ["chess/chess-1.png", "chess/chess-2.png"],
  },
  {
    title: "My Academy Help",
    desc: "A learning platform for student",
    hostURL: "https://myacademyhelp.com/",
    gitURL: "https://myacademyhelp.com/",
    cover: "mha.jpg",
    images: [],
  },
  {
    title: "Spectrum Shirts",
    desc: "Shirt design site build using ThreeJS",
    hostURL: "https://spectrum-shirts.vercel.app/",
    gitURL: "https://github.com/yube01/SpectrumShirts",
    cover: "spectrum.jpg",
    images: [],
  },
  {
    title: "Searchword",
    desc: "Dictionary website using api",
    hostURL: "https://searchword1.netlify.app",
    gitURL: "https://github.com/yube01/Dictionary",
    cover: "search.jpg",
    images: [],
  },
  // {
  //   title: "Google Drive Clone",
  //   desc: "Full stack google drive clone with MERN stack",
  //   hostURL: "https://google-drive-clones.netlify.app",
  //   gitURL: "https://github.com/yube01/google-drive-clone",
  //   cover: "googledrive.jpg",
  //   images: [],
  // },
  // {
  //   title: "CMS",
  //   desc: "College Management System.",
  //   hostURL: "https://cms-swastik.rf.gs",
  //   gitURL: "https://github.com/sijan17/cms-swastik.git",
  //   cover: "cms-cover.png",
  //   images: [
  //     "cms/cms-mob-1.png",
  //     "cms/cms-mob-2.png",
  //     "cms/cms-big-1.png",
  //     "cms/cms-big-2.png",
  //     "cms/cms-big-3.png",
  //   ],
  // },
  // {
  //   title: "Be Social",
  //   desc: "Social media clone",
  //   hostURL: "https://besocial8.netlify.app",
  //   gitURL: "https://github.com/yube01/Social-Yube",
  //   cover: "besocial.jpg",
  //   images: [],
  // },
  // {
  //   title: "UURL",
  //   desc: "URL Shortner.",
  //   hostURL: "https://test.sijan-paudel.com.np",
  //   gitURL: "https://github.com/sijan17/uurl.git",
  //   cover: "uurl-cover.png",
  //   images: ["uurl/uurl-1.png", "uurl/uurl-2.png"],
  // },
];
