export const projectData = [
  // {
  //   title: "Social Media",
  //   desc: "MERN social media app.",
  //   hostURL: "https://social-jifg.onrender.com/",
  //   gitURL: "https://github.com/sijan17/social-frontend.git",
  //   cover: "social-cover.png",
  //   images: [
  //     "social/social-mob-1.png",
  //     "social/social-mob-2.png",
  //     "social/social-mob-3.png",
  //     "social/social-1.png",
  //     "social/social.png",
  //   ],
  // },
  {
    title: "QFX Clone",
    desc: "Qfx Cinema clone website",
    hostURL: "https://qfx.netlify.app/",
    gitURL: "https://github.com/yube01/qfxclone",
    cover: "qfx1.jpg",
    // images: ["chess/chess-1.png", "chess/chess-2.png"],
  },
  {
    title: "Searchword",
    desc: "Dictionary website using api",
    hostURL: "https://searchword1.netlify.app",
    gitURL: "https://github.com/yube01/Dictionary",
    cover: "search.jpg",
    images: [],
  },
  // {
  //   title: "CMS",
  //   desc: "College Management System.",
  //   hostURL: "https://cms-swastik.rf.gs",
  //   gitURL: "https://github.com/sijan17/cms-swastik.git",
  //   cover: "cms-cover.png",
  //   images: [
  //     "cms/cms-mob-1.png",
  //     "cms/cms-mob-2.png",
  //     "cms/cms-big-1.png",
  //     "cms/cms-big-2.png",
  //     "cms/cms-big-3.png",
  //   ],
  // },
  // {
  //   title: "Be Social",
  //   desc: "Social media clone",
  //   hostURL: "https://besocial8.netlify.app",
  //   gitURL: "https://github.com/yube01/Social-Yube",
  //   cover: "besocial.jpg",
  //   images: [],
  // },
  // {
  //   title: "UURL",
  //   desc: "URL Shortner.",
  //   hostURL: "https://test.sijan-paudel.com.np",
  //   gitURL: "https://github.com/sijan17/uurl.git",
  //   cover: "uurl-cover.png",
  //   images: ["uurl/uurl-1.png", "uurl/uurl-2.png"],
  // },
];
